[env:esp32_usb]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM9
monitor_port = COM9
monitor_speed = 115200

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  emelianov/modbus-esp8266

build_flags =
  -I app
  -I config

[env:esp32_ota]
platform = espressif32
board = esp32dev
framework = arduino

upload_protocol = espota
upload_port = 10.10.10.77

upload_flags =
  --auth=factory2024

monitor_port = COM9
monitor_speed = 115200

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  emelianov/modbus-esp8266

build_flags =
  -I app
  -I config